### PR TITLE
fix(docs): update support schedule labels and dates

### LINKED ISSUE #6149: Support schedule issues
### Check existing issues

- [x] I've verified that this request isn't described by any existing issues.

### Request

Snapcraft 7 was released in 2022, so it should be:

Image

instead of 

Image

There's more overlap when you add Snapcraft 9:

Image

I tried making the version's font size the same size as the horizontal axis, but that still wasn't enough.

Also, javascript uses [0-indexes for months](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#monthindex), so the dates:

```
    startDate: new Date(2018, 4, 1),
    endDate: new Date(2023, 3, 31),
    taskName: "core18",
    type: "LTS",
  },
```

resolve `Date(..., 3, 31),` to Apr-31 which doesn't exist and becomes May-01.

### Document location

https://documentation.ubuntu.com/snapcraft/stable/reference/support-schedule/

### PR DESCRIPTION
**Pull request by gcomneno**
## Summary

Update the support schedule chart data to shorten milestone labels to version-only values (for example, `7.0.0` and `8.0.0`) and fix the April start dates in the chart data.

## Testing

- not run (docs/data-only change)

## Issue

Closes #6149

### CODE REVIEW

File: docs/_static/js/support-chart.js [hunk 1]
```diff
@@ -112,7 +112,7 @@ const dataEntries = [
 // Defines milestones. Optional.
 const dataMilestones = [
   {
-    name: "Snapcraft 7",
+    name: "Snapcraft 7.0.0",
```
Comment (mr-cal) [inline docs/_static/js/support-chart.js]: The suggestion was to shorten to just the version, since the length was the issue.
```suggestion
    name: "7.0.0",
```

**Review by medubelko — APPROVED** [review]
LGTM!
